version: '3.8'
services:
  celebrity-strike-frontend:
    image: "${DOCKERHUB_REPO}:${VERSION}"
    container_name: celebrity-strike-frontend
    restart: always
    environment:
      - PORT=18081
      - VIRTUAL_PORT=18081
      - VIRTUAL_HOST=app.celebrity-strike.duckdns.org
      - LETSENCRYPT_HOST=app.celebrity-strike.duckdns.org
      - LETSENCRYPT_EMAIL=soshinaalena6415@gmail.com
    expose:
      - "18081"
    networks:
      - celebrity_network

networks:
  celebrity_network:
    external: true
